# Generated by Django 4.2.15 on 2024-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="First_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="Last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gst",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
