# Generated by Django 4.2.15 on 2024-08-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_profile_first_name_profile_last_name_profile_gst_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="First_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="Last_name",
            new_name="last_name",
        ),
    ]
