# Generated by Django 4.2.15 on 2024-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
