# Generated by Django 4.2.15 on 2024-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_user_token_created_at_alter_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveIntegerField(),
        ),
    ]
