# Generated by Django 4.2.15 on 2024-09-02 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_payment_stripe_id_payment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
