# Generated by Django 4.2.13 on 2024-10-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
